# Generated by Django 2.2.19 on 2022-07-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_text',
            field=models.TextField(default='https://', verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Подробный текст'),
        ),
    ]
