# Generated by Django 2.2.19 on 2022-08-03 07:18

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('folder_hierarchy', '0002_auto_20220707_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Папку', 'verbose_name_plural': 'Папки'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='folder_hierarchy.Category', verbose_name='Родительская папка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Папка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='folder_hierarchy.Category', verbose_name='Название папки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='Подробный текст'),
        ),
    ]
