# Generated by Django 2.2.19 on 2022-08-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_hierarchy', '0003_auto_20220803_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book',
            field=models.FileField(blank=True, upload_to='books/'),
        ),
    ]
