# Generated by Django 2.2.19 on 2022-08-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_hierarchy', '0005_auto_20220803_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name_book',
            field=models.TextField(blank=True, verbose_name='Текст PDF-кнопки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='book',
            field=models.FileField(blank=True, upload_to='media/books/', verbose_name='PDF-файл'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст над видео'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link_text',
            field=models.TextField(blank=True, verbose_name='Ссылка на ютуб'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название видео'),
        ),
    ]
