# Generated by Django 2.2.19 on 2022-08-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_hierarchy', '0007_auto_20220803_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='book',
            field=models.FileField(blank=True, upload_to='media/books/', verbose_name='PDF-файл'),
        ),
    ]
