# Generated by Django 2.2.19 on 2022-08-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_hierarchy', '0008_auto_20220803_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='book',
            field=models.FileField(blank=True, upload_to='books/', verbose_name='PDF-файл'),
        ),
    ]
