# Generated by Django 2.2.19 on 2022-08-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_hierarchy', '0009_auto_20220803_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['serial_number'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AddField(
            model_name='post',
            name='serial_number',
            field=models.TextField(blank=True, max_length=5),
        ),
    ]
