# Generated by Django 2.2.19 on 2022-08-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_hierarchy', '0010_auto_20220806_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name_book',
            field=models.TextField(blank=True, max_length=150, verbose_name='Текст PDF-кнопки'),
        ),
    ]
