# Generated by Django 2.2.19 on 2022-08-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_hierarchy', '0011_auto_20220806_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='serial_number',
            field=models.TextField(blank=True, max_length=5, verbose_name='№п/п'),
        ),
    ]
