# Generated by Django 2.2.19 on 2022-08-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_hierarchy', '0012_auto_20220806_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='free_videos',
            field=models.BooleanField(default=False, verbose_name='Бесплатно'),
        ),
    ]
